version: '3.4'

x-default:
  &default-odoo
  tty: true
  volumes:
    - odoo-web-data:/var/lib/odoo
    - ./odoo.conf:/etc/odoo/odoo.conf:ro
    - ../../common:/mnt/common:ro
    - ./:/mnt/project:ro

  environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

services:
  matrix-bot:
    build:
      context: ./src/addons/mail_matrix/matrix-bot
      target: dev
    volumes:
      - ./src/addons/mail_matrix/matrix-bot:/app
    env_file: ".env.matrixbot"
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - ODOO_ENDPOINT=http://odoo:8069
    depends_on:
      - odoo

  odoo:
    << : *default-odoo
    build: .
    depends_on:
      - db
      - wdb
      - proxy
      - odoo-longpolling
      - smtpfake
    command: ['--dev', 'reload,qweb,werkzeug,xml',
#    '-d', 'prod6',
#    '-d', 'dev1779',
#'-d', 'dev286',
#'-d', 'dev1828',
#'-d', 'prod1778',
#'-d', 'dev1721',
#'-d', 'dev1969',
#'-d', 'prod1969',
'-d', 'prod20240930',
#'-d', 'prod1721',
#    '-u', 'tc_web,tc_mail,tc_base',
#    '-u', 'tc_mass_mailing',
#    '-u', 'tc_reports', #mass_mailing',
#'-u', 'base', #,tc_event_sale',
#'-u', 'base',
#'-u', 'tc_base,tc_reports',
#'-i', 'tc_sale',
#    '-i', 'payment_nexiit',
#    '--log-handler=odoo.addons.queue_job:DEBUG',
'-u', 'tc_event_sale',
    '--log-handler=odoo.addons.sync_whatsapp:DEBUG',
    ]
    ports:
      - "8069:8069"

  odoo-longpolling:
    << : *default-odoo
    image: my/odoo:15.0
    depends_on:
      - db
      - wdb
      - proxy
    command: ['odoo', 'gevent', '--dev', 'reload', '--addons-path', '/mnt/common/odoo/odoo/addons']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  proxy:
    image: envoyproxy/envoy-alpine:v1.10.0
    ports: ['80:80']
    volumes: ['./envoy.yaml:/etc/envoy/envoy.yaml']

  wdb:
    image: kozea/wdb:3.3.0
    init: true
    ports: ['19840:19840']

  smtpfake:
    image: mailhog/mailhog

  odoo2:
    << : *default-odoo
    build: .
    depends_on:
      - db
    command: ['--dev', 'reload,qweb,werkzeug,xml',
#    '-d', 'prod6',
#    '-d', 'dev1779',
#'-d', 'dev286',
#'-d', 'dev1828',
#'-d', 'prod1778',
#'-d', 'dev1721',
#'-d', 'dev1969',
'-d', 'prod20240911',
#'-d', 'prod1721',
#    '-u', 'tc_web,tc_mail,tc_base',
#    '-u', 'tc_mass_mailing',
#'-u', 'base', #,tc_event_sale',
#'-u', 'base',
#'-u', 'tc_mass_mailing',
#'-i', 'tc_sale',
#    '-i', 'payment_nexiit',
#    '--log-handler=odoo.addons.queue_job:DEBUG',
#    '--log-handler=odoo.addons.sync_whatsapp:DEBUG',
    ]
    ports:
      - "6366:8069"

volumes:
  odoo-web-data:
  odoo-db-data:
